default_stages: ['commit']
default_install_hook_types: [pre-commit, commit-msg, pre-push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: mixed-line-ending
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 'v3.29.0'
    hooks:
      - id: commitizen
