default_stages: ['commit']
default_install_hook_types: [pre-commit, commit-msg, pre-push]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-merge-conflict
    - id: mixed-line-ending
    - id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        args: ['-l', '100']
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.2
    hooks:
    -   id: autopep8
        args: ['-aa', '--max-line-length=100', "--in-place"]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: ['--py311-plus']
- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.4.0
  hooks:
  - id: add-trailing-comma
    args: [--py36-plus]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
        args: ['--py39-plus']
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: ['--max-line-length=100']
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
    -   id: mypy
- repo: https://github.com/commitizen-tools/commitizen
  rev: 'v2.42.1'
  hooks:
    - id: commitizen
    - id: commitizen-branch
      stages: [push]
