name: deploy

on:
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: shalzz/zola-deploy-action@v0.21.0
        env:
          BUILD_DIR: source
          BUILD_ONLY: true
          CHECK_LINKS: true
          CHECK_FLAGS: --skip-external-links

      - name: Archive artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: public/
          retention-days: 1

      - name: Deploy pages
        uses: actions/deploy-pages@v4
