name: Deploy to AWS

on:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read # This is required for actions/checkout@v2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: eu-west-3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: python -m venv .venv
      - run: .venv/bin/pip install -r requirements.txt
      - name: Deploy to s3
        uses: pulumi/actions@v3
        with:
          refresh: true
          command: up
          stack-name: prod
          work-dir: iac
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: html-website-pages
          path: build/html
