name: validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  precommit-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python (pour pre-commit)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Build
        uses: shalzz/zola-deploy-action@v0.21.0
        env:
          BUILD_DIR: source
          BUILD_ONLY: true
          CHECK_LINKS: true
          CHECK_FLAGS: --skip-external-links
